name: Run tests
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  tests:
    name: Run tests
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: NPM install
        run: npm install
      - name: Build
        run: npm run build
      - name: Run unit tests
        run: npm run test:unit
      - name: Run server
        run: npm run test:server &
      - name: Run e2e tests for chrome
        run: npm run test:e2e -- --browsers=chrome
